name: Local-K8s-CD

on: 
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Local Cluster
        run: |
          /opt/homebrew/bin/kubectl apply -f configmap.yaml
          /opt/homebrew/bin/kubectl apply -f service.yaml
          /opt/homebrew/bin/kubectl apply -f deploy.yaml
          /opt/homebrew/bin/kubectl apply -f ingress.yaml

      - name: Verify Deployment
        run: |
          /opt/homebrew/bin/kubectl rollout status deployment/my-web-server

